services:
  database:
    image: postgres:16-alpine
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=app
    ports:
      - "5432:5432"
    restart:
      on-failure
  app:
    image: trialapp
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_HOST=database

    command: /bin/sh -c 'npx sequelize db:migrate && node src/index.js'
    ports: 
      - '3000:3000'
